[build]
  base = "/"
  command = "npm run build:client"
  publish = "dist/public"
  
[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"