services:
  - type: web
    name: connectik-api
    env: node
    buildCommand: npm install --include=dev && npm run build:server
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false